version: '2'

services:

  #  The Application
  app:
    container_name: sikode_dir
    build:
      context: ./
      dockerfile: development/app.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

# The Web Server
  web:
    container_name: sikode_http
    build:
      context: ./
      dockerfile: development/web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    ports:
      - 4000:80

# The Database
  # database:
  #   container_name: sikode_db
  #   image: mysql:5.7
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   environment:
  #     - "MYSQL_DATABASE=sikode"
  #     - "MYSQL_USER=phpmyadmin"
  #     - "MYSQL_PASSWORD=phpmyadmin"
  #     - "MYSQL_ROOT_PASSWORD=yomanyongcrew."
  #   ports:
  #     - 4001:3306

# volumes:
#   dbdata: